@url_dev = http://localhost:3010/v1/api
@apikey = 20d10158c32b336eacb21e56fe392e1f12eb045bdb3c22b336c19acb68e2fb8308e6a9285a079ada9b57d584d0839632e9eee212b3d34858fa7bb1a9806575ac


### login
POST {{url_dev}}/shop/login
content-type: application/json
x-api-key: {{apikey}}

{
  "email": "shopowner14@gmail.com",
  "password": "shopowner123"
}

### 2. Copy the tokens from login response and update these variables
@client_id = 681a30936b5abdb92bd3ad37
@access_token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODFhMzA5MzZiNWFiZGI5MmJkM2FkMzciLCJlbWFpbCI6InNob3Bvd25lcjE0QGdtYWlsLmNvbSIsInN1YiI6IjY4MWEzMDkzNmI1YWJkYjkyYmQzYWQzNyIsImlhdCI6MTc0NjYxNDY3NCwiZXhwIjoxNzQ2NjE4Mjc0LCJhdWQiOiJhcGkuZXhhbXBsZS5jb20iLCJpc3MiOiJleGFtcGxlLmNvbSJ9.ik-ksNUcMetdDxFBETa3DPHZP3hBIEi99vRTfTAMGs87eqBUGOSVPpoGs0Eecy1bm-OSbB8AicoSlyTEtkpEDovd9fl4P61ukDDHgk4Y5hjQF98qUVSsc7cej7BdKMFH-2M57Ye34fRI0WkP9xNo1c1tcb-ucl8eucd3SZ0iqVQ7oC214jtnkxEDc_lwpSZi6gczWWGjIxB_VTEOR5fkelzYByjV2PpUysi1D6P7JYhbZBuHv7Jwy98Re4QzfulVQ_uyOJ7EhwwQdKv1dphCaqwTqzmhcnGNkO5Q3tDTfRUVkZucT0aQ4Umw4HHYBbJ_jqGTGcb-w2QO6HWoZhvA1z_3LBTWi_WM6CAPM69zDDsTz6fqWajLelHfQQDn0lUdV3r6bThr1CDTXKH0deO33y7CfV_uMaYmb1qntxZW4CdXAy5qTXdGLsbTr_D0QKZA3JWjmooYfqvKLJeUBKwpDkLXLsN1VjvCM6MeasI1L2EZDTe7gJgF47ib6B1jNEsg11lKjkU6oCwjnTDxG90qRtz2qT4c19LEJ5hfGcsijwZkOrY0JUICpSskBRBj3FtKKUJjj-XqyLDAQjAkKC-5kffuQ2DcW6TuVj8L31C1yCpr_f5tLCR0Lx8fS8y65KGVl711YhPrgKsZoaIrjjluf9jt2yPVv0QPEKHvn6muKTQ
@refresh_token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODFhMzA5MzZiNWFiZGI5MmJkM2FkMzciLCJlbWFpbCI6InNob3Bvd25lcjE0QGdtYWlsLmNvbSIsInN1YiI6IjY4MWEzMDkzNmI1YWJkYjkyYmQzYWQzNyIsImlhdCI6MTc0NjYxNDY3NCwiZXhwIjoxNzQ5MjA2Njc0LCJhdWQiOiJhcGkuZXhhbXBsZS5jb20iLCJpc3MiOiJleGFtcGxlLmNvbSJ9.Iomt_8niowispgUKfF2G7MFKvgRL6CZZEoBZtUowgfyem5OALNuJDjcn6oLcflTbLaHsZmVQSp6hoJyTH4pzco_c7JiLBrO6uBivgbkwe1RZsjkjzpNU5y0wR70lxLHpVSvB-K0tcn548RFqM9ag3aUgbZu9yJ_FYbaKtbpuw7oYzP63YHgW3Er3Pxd9eoFBhU7ToRlYIdQ_DhFEv7C00MOIDkZONl2z3tyQZukjZD_r9gI99uOoU-QeW2Ya8gWMK50YknupYGTPmbFKnSBYzDMJ37nyZHpID_bNcK1WBgyULeWXETE8xMROqzyZHPTeCEZzlBv0Vtc2Y3bC4TEKwUvNclTDcl-NxCz5nAxIzxOyk9VE4R1EJHggBKnYbdbc2KRx5GCFX0eUC39zi6ZYLnmmzWuIYKstFeb20EHlGwrL0FmTffBZSeZ5qaMLteU9gryyGw7ByBfpIKYzuk8RWgeltA1XVXGB-jHMXJtWi7TlYBWvl_wYb0q5j9_D113zqDNmCeLwbRmAo8iQVUVk90kY3tVAjTxA3HKq6PTFM57ORSsBcYSS5S6zbQvKgS2zX_zumKaDRRYpLcykZei8jGItSD8wCaO9G_3ImpbNwf8xb0COuQlGlUzM4PM7NLzRx7WjQLubJnS8q7Cnyrf6rCR5GgEZuvyQC6yeP4BwuYk

### 3. Then try logout
POST {{url_dev}}/shop/logout HTTP/1.1
content-type: application/json
x-api-key: {{apikey}}
x-client-id: {{client_id}}
authorization: Bearer {{access_token}}

{
  "email": "shopowner14@gmail.com",
  "password": "shopowner123"
}

### signup
POST {{url_dev}}/shop/signup HTTP/1.1
content-type: application/json
x-api-key: {{apikey}}

{
  "name": "Shop Owner 14",
  "email": "shopowner14@gmail.com",
  "password": "shopowner123"
}


### refresh token
POST {{url_dev}}/shop/refresh-token
content-type: application/json
x-api-key: {{apikey}}
x-client-id: {{client_id}}
authorization: Bearer {{access_token}}

{
  "refreshToken": "{{refresh_token}}"
}
